module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  GET_UNITS_ERROR: "GET_UNITS_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // FamilyIncome
  GET_FAMILY_INCOME_ERROR: "GET_FAMILY_INCOME_ERROR",
  ADD_FAMILY_INCOME_ERROR: "ADD_FAMILY_INCOME_ERROR",
  UPDATE_FAMILY_INCOME_ERROR: "UPDATE_FAMILY_INCOME_ERROR",
  DELETE_FAMILY_INCOME_ERROR: "DELETE_FAMILY_INCOME_ERROR",

  // IncomeType
  INCOME_TYPE_NOT_FOUND: "INCOME_TYPE_NOT_FOUND",
  GET_INCOME_TYPE_ERROR: "GET_INCOME_TYPE_ERROR",
  GET_INCOME_TYPES_ERROR: "GET_INCOME_TYPES_ERROR",
  ADD_INCOME_TYPE_ERROR: "ADD_INCOME_TYPE_ERROR",
  UPDATE_INCOME_TYPE_ERROR: "UPDATE_INCOME_TYPE_ERROR",
  DELETE_INCOME_TYPE_ERROR: "DELETE_INCOME_TYPE_ERROR",
  INCOME_TYPE_IN_USE: "INCOME_TYPE_IN_USE",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  GET_USERS_ERROR: "GET_USERS_ERROR",
  GET_USER_ERROR: "GET_USER_ERROR",
  ADD_USER_ERROR: "ADD_USER_ERROR",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
  DELETE_USER_ERROR: "DELETE_USER_ERROR",
  DELETE_USER_FORBIDDEN: "DELETE_USER_FORBIDDEN",

  // Purchase
  GET_PURCHASES_ERROR: "GET_PURCHASES_ERROR",
  ADD_PURCHASES_ERROR: "ADD_PURCHASES_ERROR",
  UPDATE_PURCHASES_ERROR: "UPDATE_PURCHASES_ERROR",
  DELETE_PURCHASES_ERROR: "DELETE_PURCHASES_ERROR",

  // Item
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
  GET_ITEM_ERROR: "GET_ITEM_ERROR",
  GET_ITEMS_ERROR: "GET_ITEMS_ERROR",
  ADD_ITEMS_ERROR: "ADD_ITEMS_ERROR",

  // Currency
  ADD_CURRENCIES_ERROR: "ADD_CURRENCIES_ERROR",
  UPDATE_CURRENCIES_ERROR: "UPDATE_CURRENCIES_ERROR",
  DELETE_CURRENCIES_ERROR: "DELETE_CURRENCIES_ERROR",
  CURRENCY_NOT_FOUND: "CURRENCY_NOT_FOUND",
  GET_CURRENCY_ERROR: "GET_CURRENCY_ERROR",
  GET_CURRENCIES_ERROR: "GET_CURRENCIES_ERROR",
  CURRENCY_IN_USE: "CURRENCY_IN_USE",

  // Items Category
  GET_CATEGORIES_ERROR: "GET_CATEGORIES_ERROR",
  EDIT_ITEMS_CATEGORY_ERROR: "EDIT_ITEMS_CATEGORY_ERROR",

  // Purchases Category Suggestion
  GET_PURCHASES_CATEGORY_SUGGESTION_ERROR:
    "GET_PURCHASES_CATEGORY_SUGGESTION_ERROR",

  // Authentication & Authorization
  REGISTER_FAILED: "REGISTER_FAILED",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  REFRESH_TOKEN_FAILED: "REFRESH_TOKEN_FAILED",
  USER_EXISTS: "USER_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  NO_AUTH_HEADER: "NO_AUTH_HEADER",
  INVALID_AUTH_HEADER: "INVALID_AUTH_HEADER",
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  DEFAULT_CURRENCY_NOT_FOUND: "DEFAULT_CURRENCY_NOT_FOUND",
  INVALID_INVITE_CODE: "INVALID_INVITE_CODE",
  MISSING_FAMILY_INFO: "MISSING_FAMILY_INFO",

  // Email Verification & Password Reset
  EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",
  SEND_VERIFICATION_EMAIL_FAILED: "SEND_VERIFICATION_EMAIL_FAILED",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
  REQUEST_PASSWORD_RESET_FAILED: "REQUEST_PASSWORD_RESET_FAILED",
  CHANGE_PASSWORD_FAILED: "CHANGE_PASSWORD_FAILED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",

  // Family Management
  FAMILY_NOT_FOUND: "FAMILY_NOT_FOUND",
  GET_FAMILY_FAILED: "GET_FAMILY_FAILED",
  GET_USER_FAILED: "GET_USER_FAILED",
};
